# Generated by Django 3.0.3 on 2020-04-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_find', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
