# Generated by Django 3.0.3 on 2020-04-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_find', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='first_name',
            field=models.TextField(default='accounts.User.get_first_name'),
        ),
        migrations.AddField(
            model_name='job',
            name='last_name',
            field=models.TextField(default='accounts.User.get_last_name'),
        ),
    ]
