# Generated by Django 3.0.3 on 2020-03-07 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('job_find', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Person'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.URLField(blank=True, max_length=115),
        ),
        migrations.AlterField(
            model_name='job',
            name='pay',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
