# Generated by Django 3.0.3 on 2020-04-22 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_find', '0002_auto_20200421_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='last_name',
        ),
    ]
