# Generated by Django 3.0.3 on 2020-04-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200418_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.TextField(default='accounts.User.get_first_name'),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.TextField(default='accounts.User.get_last_name'),
        ),
    ]
