# Generated by Django 3.0.3 on 2020-02-18 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ACC', 'Accounting'), ('BUS', 'Business Administration')], max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.TextField(blank=True, max_length=30)),
                ('tuesday', models.TextField(blank=True, max_length=30)),
                ('wednesday', models.TextField(blank=True, max_length=30)),
                ('thursday', models.TextField(blank=True, max_length=30)),
                ('friday', models.TextField(blank=True, max_length=30)),
                ('saturday', models.TextField(blank=True, max_length=30)),
                ('sunday', models.TextField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True, max_length=20)),
                ('semester', models.TextField(blank=True, max_length=10)),
                ('course_number', models.TextField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.FloatField()),
                ('credentials', models.TextField(blank=True, max_length=50)),
                ('method', models.IntegerField(choices=[(1, 'Private'), (2, 'Group'), (3, 'Either')], null=True)),
                ('location', models.IntegerField(choices=[(1, 'School'), (2, 'Anywhere'), (3, 'Other')], null=True)),
                ('description', models.TextField(blank=True, max_length=30)),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor_match.Schedule')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor_match.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjToDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor_match.Department')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor_match.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.FloatField()),
                ('standing', models.IntegerField(choices=[(1, 'Freshman'), (2, 'Sophomore'), (3, 'Junior'), (4, 'Senior'), (5, 'Graduate')], null=True)),
                ('method', models.IntegerField(choices=[(1, 'Private'), (2, 'Group'), (3, 'Either')], null=True)),
                ('location', models.IntegerField(choices=[(1, 'School'), (2, 'Anywhere'), (3, 'Other')], null=True)),
                ('description', models.TextField(blank=True, max_length=30)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor_match.Department')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor_match.Schedule')),
            ],
        ),
    ]
