# Generated by Django 3.0.2 on 2020-02-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('charges', models.BooleanField()),
                ('charge_fee', models.FloatField()),
                ('subject', models.TextField(max_length=60)),
            ],
        ),
    ]
