# Generated by Django 3.0.3 on 2020-04-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('ACC', 'Accounting'), ('ART', 'Art'), ('GPY', 'Art Therapy'), ('BIO', 'Biology'), ('BUS', 'Business Administration'), ('CHE', 'Chemistry'), ('CPY', 'Clinical Psychology'), ('COM', 'Communication'), ('CSC', 'Computer Science'), ('EDU', 'Education'), ('ENG', 'English'), ('TSL', 'English as a Second Language'), ('HSC', 'Health Sciences'), ('HST', 'History'), ('HSP', 'Human Services'), ('KIN', 'Kinesiology'), ('LBS', 'Liberal Studies'), ('MTH', 'Mathematics'), ('PHL', 'Philosophy'), ('PSC', 'Political Science'), ('PSY', 'Psychology'), ('REL', 'Religious Studies'), ('SOC', 'Sociology'), ('SPA', 'Spanish Studies')], max_length=3, null=True),
        ),
    ]
