# Generated by Django 3.0.3 on 2020-02-26 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor_match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('ACC', 'Accounting'), ('BUS', 'Business Administration'), ('MTH', 'Math')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='friday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='saturday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sunday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
