# Generated by Django 3.0.3 on 2020-03-04 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200303_1917'),
        ('tutor_match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Person'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Person'),
        ),
    ]
