# Generated by Django 3.0.3 on 2020-04-21 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_match', '0003_auto_20200420_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tutor_match.Subject'),
            preserve_default=False,
        ),
    ]
